[WIP] create be for user
TigranJaghatspanyan/sequelize-project-be pull request #1
Opened 2022-09-09 15:01 UTC by TigranJaghatspanyan

2022-09-10 14:30 UTC, TigranJaghatspanyan commented
![Screenshot 2022-09-10 182939](https://user-images.githubusercontent.com/91381312/189487916-792ebfb8-7031-4288-8ccf-49b4d802c94a.png)
![Screenshot 2022-09-10 182818](https://user-images.githubusercontent.com/91381312/189487918-a22200ad-6726-43a1-ab57-db069f94f248.png)
![Screenshot 2022-09-10 182848](https://user-images.githubusercontent.com/91381312/189487920-333353fa-3c91-4491-95d0-d049097d578b.png)
![Screenshot 2022-09-10 182900](https://user-images.githubusercontent.com/91381312/189487921-9368039a-a3b6-4d96-9888-66b2409b906a.png)

2022-09-12 06:53 UTC, SergeyGhazaryan requested changes

2022-09-12 06:53 UTC, SergeyGhazaryan commented on node-mysql-jwt/app.js
> +// app.use(express.static(path.join(__dirname, 'public')));
delete comments

2022-09-12 06:53 UTC, SergeyGhazaryan commented on node-mysql-jwt/app.js
> +app.use("/api", indexRouter);
routers names are the same

2022-09-12 06:53 UTC, SergeyGhazaryan commented on node-mysql-jwt/app.js
> +app.listen(5000, () => console.log(`Listen port `));
take `port` from env

2022-09-12 06:53 UTC, SergeyGhazaryan commented on node-mysql-jwt/config/database.js
> +};
where are you using these values?

2022-09-12 06:53 UTC, SergeyGhazaryan commented on node-mysql-jwt/controllers/auth.controllers.js
> +export const register = async (req, res) => {
In start please take all necessary values from `req.body`

F.E.` const { email, password } = req.body;

2022-09-12 06:53 UTC, SergeyGhazaryan commented on node-mysql-jwt/controllers/auth.controllers.js
> +  const id = uuidv4();
you can delete this, id (foreign key) should generate database

2022-09-12 06:53 UTC, SergeyGhazaryan commented on node-mysql-jwt/controllers/auth.controllers.js
> +    id,
delete

2022-09-12 06:53 UTC, SergeyGhazaryan commented on node-mysql-jwt/controllers/auth.controllers.js
> +  const user = await User.findOne({
In start please take all necessary values from `req.body`

2022-09-12 06:53 UTC, SergeyGhazaryan commented on node-mysql-jwt/controllers/auth.controllers.js
> +  if (user) {
check if there is no user send error message to frontend

2022-09-12 06:53 UTC, SergeyGhazaryan commented on node-mysql-jwt/controllers/auth.controllers.js
> +    if (isMatched) {
check if `isMatched` is `false` so send error message to frontend

2022-09-12 06:53 UTC, SergeyGhazaryan commented on node-mysql-jwt/controllers/auth.controllers.js
> +  return res.json({ message: "Logged out successfully" });
You must disable req.user on logout

2022-09-12 06:53 UTC, SergeyGhazaryan commented on node-mysql-jwt/env.js
> +  JWT_SECRET: "baurishvonces",
take these values from `env` and give default values too with the help of this `??` operator

2022-09-12 06:53 UTC, SergeyGhazaryan commented on node-mysql-jwt/models/user.model.js
> +export default User
add line

2022-09-12 06:53 UTC, SergeyGhazaryan commented on node-mysql-jwt/models/user.model.js
> +    updatedAt: "updated_at",
I think here you need to give types

2022-09-12 06:53 UTC, SergeyGhazaryan commented on node-mysql-jwt/node-jwt.sql
> +--
did you wrote this manually?

2022-09-12 06:53 UTC, SergeyGhazaryan commented on node-mysql-jwt/middleware/auth.guard.js
> +export default async (req, res, next) => {
can you please give name to functions?

2022-09-12 06:53 UTC, SergeyGhazaryan commented on node-mysql-jwt/routes/users.js
> +export default router;
delete this

2022-09-12 06:53 UTC, SergeyGhazaryan commented on node-mysql-jwt/utils/cache.js
> +import Keyv from "keyv"
`;`

2022-09-12 06:53 UTC, SergeyGhazaryan commented on node-mysql-jwt/utils/cache.js
> +export default keyv
`;` and please explain what this file is for?

2022-09-12 06:53 UTC, SergeyGhazaryan commented on node-mysql-jwt/utils/validator.js
> +export default (type) => (req, res, next) => {
give type to functions in all places

2022-09-12 06:53 UTC, SergeyGhazaryan commented on user-app/public/manifest.json
> +}
delete this

2022-09-12 06:53 UTC, SergeyGhazaryan commented on user-app/src/App.css
> +}
is this needed?

2022-09-12 06:53 UTC, SergeyGhazaryan commented on user-app/src/App.js
> +            <Route path="signUp" element={<SignUp />} />
use constants for redirect urls

2022-09-12 06:53 UTC, SergeyGhazaryan commented on user-app/src/App.test.js
> +});
delete this

2022-09-12 06:53 UTC, SergeyGhazaryan commented on user-app/src/Components/homePage/homePage.module.scss
> +.logOut {
add line

2022-09-12 06:53 UTC, SergeyGhazaryan commented on user-app/src/Components/homePage/index.jsx
> +import styles from "./homePage.module.scss";
move to bottom

2022-09-12 06:53 UTC, SergeyGhazaryan commented on user-app/src/Components/homePage/index.jsx
> +  });
create the separate services for api calls

2022-09-12 06:53 UTC, SergeyGhazaryan commented on user-app/src/Components/homePage/index.jsx
> +  axios.get("http://localhost:5000/user").then((res) => {
take value from env

2022-09-12 06:53 UTC, SergeyGhazaryan commented on user-app/src/Components/homePage/index.jsx
> +    });
move this logic to servec and instead of `.then()` use `await`

2022-09-12 06:53 UTC, SergeyGhazaryan commented on user-app/src/Components/homePage/index.jsx
> +    window.localStorage.removeItem("token");
here you need to call `logout` api from FE

2022-09-12 06:53 UTC, SergeyGhazaryan commented on user-app/src/Components/homePage/index.jsx
> +        <Link to="/signUp" className={styles.logOut} onClick={logOut}>
use constant for redirect url

2022-09-12 06:53 UTC, SergeyGhazaryan commented on user-app/src/Components/signIn/index.jsx
> +      });
create the separate service for api calls and instead of `.then()` use `async await`

2022-09-12 06:53 UTC, SergeyGhazaryan commented on user-app/src/Components/signIn/signin.module.scss
> +.loginContainer {
add empty lines after and before classes

2022-09-12 06:53 UTC, SergeyGhazaryan commented on user-app/src/Components/signIn/signin.module.scss
> +  background-color: black;
use the same format for all colors

2022-09-12 06:53 UTC, SergeyGhazaryan commented on user-app/src/Components/signUp/index.jsx
> +      });
I've wrote already about this

2022-09-12 06:53 UTC, SergeyGhazaryan commented on user-app/src/Components/signUp/signup.module.scss
> +.loginContainer {
the same

2022-09-12 06:53 UTC, SergeyGhazaryan commented on user-app/src/reportWebVitals.js
> +export default reportWebVitals;
is this needed?

2022-09-12 12:42 UTC, SergeyGhazaryan requested changes

2022-09-12 12:42 UTC, SergeyGhazaryan commented on node-mysql-jwt/config/database.js
> +export default {
use name too

2022-09-12 12:42 UTC, SergeyGhazaryan commented on node-mysql-jwt/config/jwt.js
> +export default {
create object for constants and export that

2022-09-12 12:42 UTC, SergeyGhazaryan commented on node-mysql-jwt/public/index.html
> +</html>
is this needed?

2022-09-12 12:42 UTC, SergeyGhazaryan commented on user-app/src/App.css
> +}
please delete this

2022-09-12 12:42 UTC, SergeyGhazaryan commented on user-app/src/App.js
> +import "./App.css";
move to bottom

2022-09-12 12:42 UTC, SergeyGhazaryan commented on user-app/src/Components/homePage/index.jsx
> +    });
the same

2022-09-12 12:42 UTC, SergeyGhazaryan commented on user-app/src/Components/homePage/index.jsx
> +  return (
add line

2022-09-12 12:42 UTC, SergeyGhazaryan commented on user-app/src/Components/signIn/index.jsx
> +          }}
write the separate async function for this and in that function call api with the help of await

2022-09-12 12:42 UTC, SergeyGhazaryan commented on user-app/src/Components/signUp/index.jsx
> +          }}
the same

2022-09-12 12:42 UTC, SergeyGhazaryan commented on user-app/src/const/env.js
> +};
take value from env

2022-09-12 12:42 UTC, SergeyGhazaryan commented on user-app/src/const/redirect.js
> +const redirect = {
change name to `redirectUrls`

2022-09-12 12:42 UTC, SergeyGhazaryan commented on user-app/src/service/axiosInstance.js
> +export default axiosInstance;
add line

2022-09-12 12:43 UTC, SergeyGhazaryan commented
All api calls write in services and use `async/await` instead of `.then()`

2022-09-12 14:44 UTC, SergeyGhazaryan commented on node-mysql-jwt/env.js
> +export default env;
+

2022-09-12 14:44 UTC, SergeyGhazaryan commented on node-mysql-jwt/models/user.model.js
> +    updatedAt: "updated_at",
+

2022-09-14 11:31 UTC, SergeyGhazaryan requested changes

2022-09-14 11:31 UTC, SergeyGhazaryan commented on node-mysql-jwt/controllers/auth.controllers.js
> +  if (user) {
first check if there is on user so throw exception

2022-09-14 11:31 UTC, SergeyGhazaryan commented on node-mysql-jwt/controllers/auth.controllers.js
> +    const token = await jwt.createToken({ id: user });
why you give user to id?

2022-09-14 11:31 UTC, SergeyGhazaryan commented on node-mysql-jwt/controllers/auth.controllers.js
> +  await cache.set(token, token, milliseconds);
why you set token 2 time?

2022-09-14 11:31 UTC, SergeyGhazaryan commented on node-mysql-jwt/models/user.model.js
> +    updatedAt: "updated_at",
there are no types

2022-09-14 11:31 UTC, SergeyGhazaryan commented on user-app/.env.example
> +BE_HOST=http://localhost:5000
add line

2022-09-14 11:31 UTC, SergeyGhazaryan commented on user-app/src/App.js
> +import { BrowserRouter, Routes, Route } from "react-router-dom";
move to top

2022-09-14 11:31 UTC, SergeyGhazaryan commented on user-app/src/Components/homePage/index.jsx
> +  });
what is this?

2022-09-14 11:31 UTC, SergeyGhazaryan commented on user-app/src/Components/signIn/index.jsx
> +    await signIn(email, password, navigate);
after signin and signup you need to save token in localstorage, and after that you can get that from storage and put in authorization header for api calls (axios)

2022-09-14 11:31 UTC, SergeyGhazaryan commented on user-app/src/service/authService.js
> +    navigate(`/${redirectUrls.login}`);
not needed any logic in services except of api calls, you can navigate in that place where you call this function

2022-09-14 11:31 UTC, SergeyGhazaryan commented on user-app/src/service/authService.js
> +    navigate(`${redirectUrls.home}`);
the same

2022-09-14 11:31 UTC, SergeyGhazaryan commented on user-app/src/service/authService.js
> +    window.localStorage.setItem("token", response.data.access_token);
the same

2022-09-14 11:31 UTC, SergeyGhazaryan commented on user-app/src/service/authService.js
> +    }
?

2022-09-14 11:31 UTC, SergeyGhazaryan commented on user-app/src/service/authService.js
> +      token,
related to this api, you need to disable req.user and send status for success, after that if it is return true delete token from storage

2022-09-14 11:31 UTC, SergeyGhazaryan commented on user-app/src/service/axiosInstance.js
> +console.log(env,"env");
delete

2022-09-14 11:31 UTC, SergeyGhazaryan commented on user-app/src/service/axiosInstance.js
> +const axiosInstance = axios.create({
add `timeout` too

2022-09-14 11:31 UTC, SergeyGhazaryan commented on user-app/src/service/authService.js
> +export const users = async (name) => {
change the name

2023-01-04 10:52 UTC, merged